// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EtcMsg.proto

#ifndef PROTOBUF_EtcMsg_2eproto__INCLUDED
#define PROTOBUF_EtcMsg_2eproto__INCLUDED

#include <string>
#include "type/type_factory.h"
#include "opcode/EtcMsgOpcode.h"
#include "module/message/MessageDefines.h"
#include "etc/etc_config.h"

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#undef GetMessage

namespace Model {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_EtcMsg_2eproto();
void protobuf_AssignDesc_EtcMsg_2eproto();
void protobuf_ShutdownFile_EtcMsg_2eproto();

class A2L_ObjectAddRequest;
class A2L_ObjectGetRequest;
class A2L_ObjectLockRequest;
class A2L_ObjectRemoveRequest;
class A2L_ObjectUnLockRequest;
class ActorRequest;
class ActorResponse;
class L2A_ObjectAddResponse;
class L2A_ObjectGetResponse;
class L2A_ObjectLockResponse;
class L2A_ObjectRemoveResponse;
class L2A_ObjectUnLockResponse;

// ===================================================================

class ActorRequest : public IActorRequest /* @@protoc_insertion_point(class_definition:Model.ActorRequest) */ {
 public:
  ActorRequest();
  virtual ~ActorRequest();

  ActorRequest(const ActorRequest& from);

  inline ActorRequest& operator=(const ActorRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActorRequest& default_instance();

  void Swap(ActorRequest* other);

  // implements Message ----------------------------------------------

  inline ActorRequest* New() const { return New(NULL); }

  ActorRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  virtual int32_t GetRpcId()const override {return rpcid();}
  virtual void SetRpcId(const int32_t val)override { set_rpcid(val);}
  virtual uint16_t GetOpcode()const override {return EtcMsgOpcode::ActorRequest;}
  virtual Type GetType()const override {return typeof(ActorRequest);}
  virtual EMessageType GetMessageType()const override {return EMessageType::IActorRequest;}
  void CopyFrom(const ActorRequest& from);
  void MergeFrom(const ActorRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ActorRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 RpcId = 90;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 90;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Model.ActorRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 rpcid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EtcMsg_2eproto();
  friend void protobuf_AssignDesc_EtcMsg_2eproto();
  friend void protobuf_ShutdownFile_EtcMsg_2eproto();

  void InitAsDefaultInstance();
  static ActorRequest* default_instance_;
};
// -------------------------------------------------------------------

class ActorResponse : public IActorResponse /* @@protoc_insertion_point(class_definition:Model.ActorResponse) */ {
 public:
  ActorResponse();
  virtual ~ActorResponse();

  ActorResponse(const ActorResponse& from);

  inline ActorResponse& operator=(const ActorResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActorResponse& default_instance();

  void Swap(ActorResponse* other);

  // implements Message ----------------------------------------------

  inline ActorResponse* New() const { return New(NULL); }

  ActorResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  virtual int32_t GetError()const override {return error();}
  virtual void SetError(const int32_t val)override { set_error(val);}
  virtual const ::std::string& GetMessage()const override {return message();}
  virtual void SetMessage(const ::std::string& val)override { set_message(val);}
  virtual int32_t GetRpcId()const override {return rpcid();}
  virtual void SetRpcId(const int32_t val)override { set_rpcid(val);}
  virtual uint16_t GetOpcode()const override {return EtcMsgOpcode::ActorResponse;}
  virtual Type GetType()const override {return typeof(ActorResponse);}
  virtual EMessageType GetMessageType()const override {return EMessageType::IActorResponse;}
  void CopyFrom(const ActorResponse& from);
  void MergeFrom(const ActorResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ActorResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 RpcId = 90;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 90;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // optional int32 Error = 91;
  void clear_error();
  static const int kErrorFieldNumber = 91;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // optional string Message = 92;
  void clear_message();
  static const int kMessageFieldNumber = 92;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:Model.ActorResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 rpcid_;
  ::google::protobuf::int32 error_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EtcMsg_2eproto();
  friend void protobuf_AssignDesc_EtcMsg_2eproto();
  friend void protobuf_ShutdownFile_EtcMsg_2eproto();

  void InitAsDefaultInstance();
  static ActorResponse* default_instance_;
};
// -------------------------------------------------------------------

class A2L_ObjectAddRequest : public IActorRequest /* @@protoc_insertion_point(class_definition:Model.A2L_ObjectAddRequest) */ {
 public:
  A2L_ObjectAddRequest();
  virtual ~A2L_ObjectAddRequest();

  A2L_ObjectAddRequest(const A2L_ObjectAddRequest& from);

  inline A2L_ObjectAddRequest& operator=(const A2L_ObjectAddRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const A2L_ObjectAddRequest& default_instance();

  void Swap(A2L_ObjectAddRequest* other);

  // implements Message ----------------------------------------------

  inline A2L_ObjectAddRequest* New() const { return New(NULL); }

  A2L_ObjectAddRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  virtual int32_t GetRpcId()const override {return rpcid();}
  virtual void SetRpcId(const int32_t val)override { set_rpcid(val);}
  virtual uint16_t GetOpcode()const override {return EtcMsgOpcode::A2L_ObjectAddRequest;}
  virtual Type GetType()const override {return typeof(A2L_ObjectAddRequest);}
  virtual EMessageType GetMessageType()const override {return EMessageType::IActorRequest;}
  void CopyFrom(const A2L_ObjectAddRequest& from);
  void MergeFrom(const A2L_ObjectAddRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(A2L_ObjectAddRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 RpcId = 90;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 90;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // optional int64 Key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  ::google::protobuf::int64 key() const;
  void set_key(::google::protobuf::int64 value);

  // optional int64 InstanceId = 2;
  void clear_instanceid();
  static const int kInstanceIdFieldNumber = 2;
  ::google::protobuf::int64 instanceid() const;
  void set_instanceid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Model.A2L_ObjectAddRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 key_;
  ::google::protobuf::int64 instanceid_;
  ::google::protobuf::int32 rpcid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EtcMsg_2eproto();
  friend void protobuf_AssignDesc_EtcMsg_2eproto();
  friend void protobuf_ShutdownFile_EtcMsg_2eproto();

  void InitAsDefaultInstance();
  static A2L_ObjectAddRequest* default_instance_;
};
// -------------------------------------------------------------------

class L2A_ObjectAddResponse : public IActorResponse /* @@protoc_insertion_point(class_definition:Model.L2A_ObjectAddResponse) */ {
 public:
  L2A_ObjectAddResponse();
  virtual ~L2A_ObjectAddResponse();

  L2A_ObjectAddResponse(const L2A_ObjectAddResponse& from);

  inline L2A_ObjectAddResponse& operator=(const L2A_ObjectAddResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const L2A_ObjectAddResponse& default_instance();

  void Swap(L2A_ObjectAddResponse* other);

  // implements Message ----------------------------------------------

  inline L2A_ObjectAddResponse* New() const { return New(NULL); }

  L2A_ObjectAddResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  virtual int32_t GetError()const override {return error();}
  virtual void SetError(const int32_t val)override { set_error(val);}
  virtual const ::std::string& GetMessage()const override {return message();}
  virtual void SetMessage(const ::std::string& val)override { set_message(val);}
  virtual int32_t GetRpcId()const override {return rpcid();}
  virtual void SetRpcId(const int32_t val)override { set_rpcid(val);}
  virtual uint16_t GetOpcode()const override {return EtcMsgOpcode::L2A_ObjectAddResponse;}
  virtual Type GetType()const override {return typeof(L2A_ObjectAddResponse);}
  virtual EMessageType GetMessageType()const override {return EMessageType::IActorResponse;}
  void CopyFrom(const L2A_ObjectAddResponse& from);
  void MergeFrom(const L2A_ObjectAddResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(L2A_ObjectAddResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 RpcId = 90;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 90;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // optional int32 Error = 91;
  void clear_error();
  static const int kErrorFieldNumber = 91;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // optional string Message = 92;
  void clear_message();
  static const int kMessageFieldNumber = 92;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:Model.L2A_ObjectAddResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 rpcid_;
  ::google::protobuf::int32 error_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EtcMsg_2eproto();
  friend void protobuf_AssignDesc_EtcMsg_2eproto();
  friend void protobuf_ShutdownFile_EtcMsg_2eproto();

  void InitAsDefaultInstance();
  static L2A_ObjectAddResponse* default_instance_;
};
// -------------------------------------------------------------------

class A2L_ObjectLockRequest : public IActorRequest /* @@protoc_insertion_point(class_definition:Model.A2L_ObjectLockRequest) */ {
 public:
  A2L_ObjectLockRequest();
  virtual ~A2L_ObjectLockRequest();

  A2L_ObjectLockRequest(const A2L_ObjectLockRequest& from);

  inline A2L_ObjectLockRequest& operator=(const A2L_ObjectLockRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const A2L_ObjectLockRequest& default_instance();

  void Swap(A2L_ObjectLockRequest* other);

  // implements Message ----------------------------------------------

  inline A2L_ObjectLockRequest* New() const { return New(NULL); }

  A2L_ObjectLockRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  virtual int32_t GetRpcId()const override {return rpcid();}
  virtual void SetRpcId(const int32_t val)override { set_rpcid(val);}
  virtual uint16_t GetOpcode()const override {return EtcMsgOpcode::A2L_ObjectLockRequest;}
  virtual Type GetType()const override {return typeof(A2L_ObjectLockRequest);}
  virtual EMessageType GetMessageType()const override {return EMessageType::IActorRequest;}
  void CopyFrom(const A2L_ObjectLockRequest& from);
  void MergeFrom(const A2L_ObjectLockRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(A2L_ObjectLockRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 RpcId = 90;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 90;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // optional int64 Key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  ::google::protobuf::int64 key() const;
  void set_key(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Model.A2L_ObjectLockRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 key_;
  ::google::protobuf::int32 rpcid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EtcMsg_2eproto();
  friend void protobuf_AssignDesc_EtcMsg_2eproto();
  friend void protobuf_ShutdownFile_EtcMsg_2eproto();

  void InitAsDefaultInstance();
  static A2L_ObjectLockRequest* default_instance_;
};
// -------------------------------------------------------------------

class L2A_ObjectLockResponse : public IActorResponse /* @@protoc_insertion_point(class_definition:Model.L2A_ObjectLockResponse) */ {
 public:
  L2A_ObjectLockResponse();
  virtual ~L2A_ObjectLockResponse();

  L2A_ObjectLockResponse(const L2A_ObjectLockResponse& from);

  inline L2A_ObjectLockResponse& operator=(const L2A_ObjectLockResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const L2A_ObjectLockResponse& default_instance();

  void Swap(L2A_ObjectLockResponse* other);

  // implements Message ----------------------------------------------

  inline L2A_ObjectLockResponse* New() const { return New(NULL); }

  L2A_ObjectLockResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  virtual int32_t GetError()const override {return error();}
  virtual void SetError(const int32_t val)override { set_error(val);}
  virtual const ::std::string& GetMessage()const override {return message();}
  virtual void SetMessage(const ::std::string& val)override { set_message(val);}
  virtual int32_t GetRpcId()const override {return rpcid();}
  virtual void SetRpcId(const int32_t val)override { set_rpcid(val);}
  virtual uint16_t GetOpcode()const override {return EtcMsgOpcode::L2A_ObjectLockResponse;}
  virtual Type GetType()const override {return typeof(L2A_ObjectLockResponse);}
  virtual EMessageType GetMessageType()const override {return EMessageType::IActorResponse;}
  void CopyFrom(const L2A_ObjectLockResponse& from);
  void MergeFrom(const L2A_ObjectLockResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(L2A_ObjectLockResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 RpcId = 90;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 90;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // optional int32 Error = 91;
  void clear_error();
  static const int kErrorFieldNumber = 91;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // optional string Message = 92;
  void clear_message();
  static const int kMessageFieldNumber = 92;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:Model.L2A_ObjectLockResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 rpcid_;
  ::google::protobuf::int32 error_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EtcMsg_2eproto();
  friend void protobuf_AssignDesc_EtcMsg_2eproto();
  friend void protobuf_ShutdownFile_EtcMsg_2eproto();

  void InitAsDefaultInstance();
  static L2A_ObjectLockResponse* default_instance_;
};
// -------------------------------------------------------------------

class A2L_ObjectUnLockRequest : public IActorRequest /* @@protoc_insertion_point(class_definition:Model.A2L_ObjectUnLockRequest) */ {
 public:
  A2L_ObjectUnLockRequest();
  virtual ~A2L_ObjectUnLockRequest();

  A2L_ObjectUnLockRequest(const A2L_ObjectUnLockRequest& from);

  inline A2L_ObjectUnLockRequest& operator=(const A2L_ObjectUnLockRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const A2L_ObjectUnLockRequest& default_instance();

  void Swap(A2L_ObjectUnLockRequest* other);

  // implements Message ----------------------------------------------

  inline A2L_ObjectUnLockRequest* New() const { return New(NULL); }

  A2L_ObjectUnLockRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  virtual int32_t GetRpcId()const override {return rpcid();}
  virtual void SetRpcId(const int32_t val)override { set_rpcid(val);}
  virtual uint16_t GetOpcode()const override {return EtcMsgOpcode::A2L_ObjectUnLockRequest;}
  virtual Type GetType()const override {return typeof(A2L_ObjectUnLockRequest);}
  virtual EMessageType GetMessageType()const override {return EMessageType::IActorRequest;}
  void CopyFrom(const A2L_ObjectUnLockRequest& from);
  void MergeFrom(const A2L_ObjectUnLockRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(A2L_ObjectUnLockRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 RpcId = 90;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 90;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // optional int64 Key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  ::google::protobuf::int64 key() const;
  void set_key(::google::protobuf::int64 value);

  // optional int64 OldInstanceId = 2;
  void clear_oldinstanceid();
  static const int kOldInstanceIdFieldNumber = 2;
  ::google::protobuf::int64 oldinstanceid() const;
  void set_oldinstanceid(::google::protobuf::int64 value);

  // optional int64 InstanceId = 3;
  void clear_instanceid();
  static const int kInstanceIdFieldNumber = 3;
  ::google::protobuf::int64 instanceid() const;
  void set_instanceid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Model.A2L_ObjectUnLockRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 key_;
  ::google::protobuf::int64 oldinstanceid_;
  ::google::protobuf::int64 instanceid_;
  ::google::protobuf::int32 rpcid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EtcMsg_2eproto();
  friend void protobuf_AssignDesc_EtcMsg_2eproto();
  friend void protobuf_ShutdownFile_EtcMsg_2eproto();

  void InitAsDefaultInstance();
  static A2L_ObjectUnLockRequest* default_instance_;
};
// -------------------------------------------------------------------

class L2A_ObjectUnLockResponse : public IActorResponse /* @@protoc_insertion_point(class_definition:Model.L2A_ObjectUnLockResponse) */ {
 public:
  L2A_ObjectUnLockResponse();
  virtual ~L2A_ObjectUnLockResponse();

  L2A_ObjectUnLockResponse(const L2A_ObjectUnLockResponse& from);

  inline L2A_ObjectUnLockResponse& operator=(const L2A_ObjectUnLockResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const L2A_ObjectUnLockResponse& default_instance();

  void Swap(L2A_ObjectUnLockResponse* other);

  // implements Message ----------------------------------------------

  inline L2A_ObjectUnLockResponse* New() const { return New(NULL); }

  L2A_ObjectUnLockResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  virtual int32_t GetError()const override {return error();}
  virtual void SetError(const int32_t val)override { set_error(val);}
  virtual const ::std::string& GetMessage()const override {return message();}
  virtual void SetMessage(const ::std::string& val)override { set_message(val);}
  virtual int32_t GetRpcId()const override {return rpcid();}
  virtual void SetRpcId(const int32_t val)override { set_rpcid(val);}
  virtual uint16_t GetOpcode()const override {return EtcMsgOpcode::L2A_ObjectUnLockResponse;}
  virtual Type GetType()const override {return typeof(L2A_ObjectUnLockResponse);}
  virtual EMessageType GetMessageType()const override {return EMessageType::IActorResponse;}
  void CopyFrom(const L2A_ObjectUnLockResponse& from);
  void MergeFrom(const L2A_ObjectUnLockResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(L2A_ObjectUnLockResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 RpcId = 90;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 90;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // optional int32 Error = 91;
  void clear_error();
  static const int kErrorFieldNumber = 91;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // optional string Message = 92;
  void clear_message();
  static const int kMessageFieldNumber = 92;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:Model.L2A_ObjectUnLockResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 rpcid_;
  ::google::protobuf::int32 error_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EtcMsg_2eproto();
  friend void protobuf_AssignDesc_EtcMsg_2eproto();
  friend void protobuf_ShutdownFile_EtcMsg_2eproto();

  void InitAsDefaultInstance();
  static L2A_ObjectUnLockResponse* default_instance_;
};
// -------------------------------------------------------------------

class A2L_ObjectRemoveRequest : public IActorRequest /* @@protoc_insertion_point(class_definition:Model.A2L_ObjectRemoveRequest) */ {
 public:
  A2L_ObjectRemoveRequest();
  virtual ~A2L_ObjectRemoveRequest();

  A2L_ObjectRemoveRequest(const A2L_ObjectRemoveRequest& from);

  inline A2L_ObjectRemoveRequest& operator=(const A2L_ObjectRemoveRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const A2L_ObjectRemoveRequest& default_instance();

  void Swap(A2L_ObjectRemoveRequest* other);

  // implements Message ----------------------------------------------

  inline A2L_ObjectRemoveRequest* New() const { return New(NULL); }

  A2L_ObjectRemoveRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  virtual int32_t GetRpcId()const override {return rpcid();}
  virtual void SetRpcId(const int32_t val)override { set_rpcid(val);}
  virtual uint16_t GetOpcode()const override {return EtcMsgOpcode::A2L_ObjectRemoveRequest;}
  virtual Type GetType()const override {return typeof(A2L_ObjectRemoveRequest);}
  virtual EMessageType GetMessageType()const override {return EMessageType::IActorRequest;}
  void CopyFrom(const A2L_ObjectRemoveRequest& from);
  void MergeFrom(const A2L_ObjectRemoveRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(A2L_ObjectRemoveRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 RpcId = 90;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 90;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // optional int64 Key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  ::google::protobuf::int64 key() const;
  void set_key(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Model.A2L_ObjectRemoveRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 key_;
  ::google::protobuf::int32 rpcid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EtcMsg_2eproto();
  friend void protobuf_AssignDesc_EtcMsg_2eproto();
  friend void protobuf_ShutdownFile_EtcMsg_2eproto();

  void InitAsDefaultInstance();
  static A2L_ObjectRemoveRequest* default_instance_;
};
// -------------------------------------------------------------------

class L2A_ObjectRemoveResponse : public IActorResponse /* @@protoc_insertion_point(class_definition:Model.L2A_ObjectRemoveResponse) */ {
 public:
  L2A_ObjectRemoveResponse();
  virtual ~L2A_ObjectRemoveResponse();

  L2A_ObjectRemoveResponse(const L2A_ObjectRemoveResponse& from);

  inline L2A_ObjectRemoveResponse& operator=(const L2A_ObjectRemoveResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const L2A_ObjectRemoveResponse& default_instance();

  void Swap(L2A_ObjectRemoveResponse* other);

  // implements Message ----------------------------------------------

  inline L2A_ObjectRemoveResponse* New() const { return New(NULL); }

  L2A_ObjectRemoveResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  virtual int32_t GetError()const override {return error();}
  virtual void SetError(const int32_t val)override { set_error(val);}
  virtual const ::std::string& GetMessage()const override {return message();}
  virtual void SetMessage(const ::std::string& val)override { set_message(val);}
  virtual int32_t GetRpcId()const override {return rpcid();}
  virtual void SetRpcId(const int32_t val)override { set_rpcid(val);}
  virtual uint16_t GetOpcode()const override {return EtcMsgOpcode::L2A_ObjectRemoveResponse;}
  virtual Type GetType()const override {return typeof(L2A_ObjectRemoveResponse);}
  virtual EMessageType GetMessageType()const override {return EMessageType::IActorResponse;}
  void CopyFrom(const L2A_ObjectRemoveResponse& from);
  void MergeFrom(const L2A_ObjectRemoveResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(L2A_ObjectRemoveResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 RpcId = 90;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 90;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // optional int32 Error = 91;
  void clear_error();
  static const int kErrorFieldNumber = 91;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // optional string Message = 92;
  void clear_message();
  static const int kMessageFieldNumber = 92;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:Model.L2A_ObjectRemoveResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 rpcid_;
  ::google::protobuf::int32 error_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EtcMsg_2eproto();
  friend void protobuf_AssignDesc_EtcMsg_2eproto();
  friend void protobuf_ShutdownFile_EtcMsg_2eproto();

  void InitAsDefaultInstance();
  static L2A_ObjectRemoveResponse* default_instance_;
};
// -------------------------------------------------------------------

class A2L_ObjectGetRequest : public IActorRequest /* @@protoc_insertion_point(class_definition:Model.A2L_ObjectGetRequest) */ {
 public:
  A2L_ObjectGetRequest();
  virtual ~A2L_ObjectGetRequest();

  A2L_ObjectGetRequest(const A2L_ObjectGetRequest& from);

  inline A2L_ObjectGetRequest& operator=(const A2L_ObjectGetRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const A2L_ObjectGetRequest& default_instance();

  void Swap(A2L_ObjectGetRequest* other);

  // implements Message ----------------------------------------------

  inline A2L_ObjectGetRequest* New() const { return New(NULL); }

  A2L_ObjectGetRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  virtual int32_t GetRpcId()const override {return rpcid();}
  virtual void SetRpcId(const int32_t val)override { set_rpcid(val);}
  virtual uint16_t GetOpcode()const override {return EtcMsgOpcode::A2L_ObjectGetRequest;}
  virtual Type GetType()const override {return typeof(A2L_ObjectGetRequest);}
  virtual EMessageType GetMessageType()const override {return EMessageType::IActorRequest;}
  void CopyFrom(const A2L_ObjectGetRequest& from);
  void MergeFrom(const A2L_ObjectGetRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(A2L_ObjectGetRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 RpcId = 90;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 90;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // optional int64 Key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  ::google::protobuf::int64 key() const;
  void set_key(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Model.A2L_ObjectGetRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 key_;
  ::google::protobuf::int32 rpcid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EtcMsg_2eproto();
  friend void protobuf_AssignDesc_EtcMsg_2eproto();
  friend void protobuf_ShutdownFile_EtcMsg_2eproto();

  void InitAsDefaultInstance();
  static A2L_ObjectGetRequest* default_instance_;
};
// -------------------------------------------------------------------

class L2A_ObjectGetResponse : public IActorResponse /* @@protoc_insertion_point(class_definition:Model.L2A_ObjectGetResponse) */ {
 public:
  L2A_ObjectGetResponse();
  virtual ~L2A_ObjectGetResponse();

  L2A_ObjectGetResponse(const L2A_ObjectGetResponse& from);

  inline L2A_ObjectGetResponse& operator=(const L2A_ObjectGetResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const L2A_ObjectGetResponse& default_instance();

  void Swap(L2A_ObjectGetResponse* other);

  // implements Message ----------------------------------------------

  inline L2A_ObjectGetResponse* New() const { return New(NULL); }

  L2A_ObjectGetResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  virtual int32_t GetError()const override {return error();}
  virtual void SetError(const int32_t val)override { set_error(val);}
  virtual const ::std::string& GetMessage()const override {return message();}
  virtual void SetMessage(const ::std::string& val)override { set_message(val);}
  virtual int32_t GetRpcId()const override {return rpcid();}
  virtual void SetRpcId(const int32_t val)override { set_rpcid(val);}
  virtual uint16_t GetOpcode()const override {return EtcMsgOpcode::L2A_ObjectGetResponse;}
  virtual Type GetType()const override {return typeof(L2A_ObjectGetResponse);}
  virtual EMessageType GetMessageType()const override {return EMessageType::IActorResponse;}
  void CopyFrom(const L2A_ObjectGetResponse& from);
  void MergeFrom(const L2A_ObjectGetResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(L2A_ObjectGetResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 RpcId = 90;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 90;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // optional int32 Error = 91;
  void clear_error();
  static const int kErrorFieldNumber = 91;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // optional string Message = 92;
  void clear_message();
  static const int kMessageFieldNumber = 92;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // optional int64 InstanceId = 1;
  void clear_instanceid();
  static const int kInstanceIdFieldNumber = 1;
  ::google::protobuf::int64 instanceid() const;
  void set_instanceid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Model.L2A_ObjectGetResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 rpcid_;
  ::google::protobuf::int32 error_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int64 instanceid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EtcMsg_2eproto();
  friend void protobuf_AssignDesc_EtcMsg_2eproto();
  friend void protobuf_ShutdownFile_EtcMsg_2eproto();

  void InitAsDefaultInstance();
  static L2A_ObjectGetResponse* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ActorRequest

// optional int32 RpcId = 90;
inline void ActorRequest::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 ActorRequest::rpcid() const {
  // @@protoc_insertion_point(field_get:Model.ActorRequest.RpcId)
  return rpcid_;
}
inline void ActorRequest::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:Model.ActorRequest.RpcId)
}

// -------------------------------------------------------------------

// ActorResponse

// optional int32 RpcId = 90;
inline void ActorResponse::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 ActorResponse::rpcid() const {
  // @@protoc_insertion_point(field_get:Model.ActorResponse.RpcId)
  return rpcid_;
}
inline void ActorResponse::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:Model.ActorResponse.RpcId)
}

// optional int32 Error = 91;
inline void ActorResponse::clear_error() {
  error_ = 0;
}
inline ::google::protobuf::int32 ActorResponse::error() const {
  // @@protoc_insertion_point(field_get:Model.ActorResponse.Error)
  return error_;
}
inline void ActorResponse::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:Model.ActorResponse.Error)
}

// optional string Message = 92;
inline void ActorResponse::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ActorResponse::message() const {
  // @@protoc_insertion_point(field_get:Model.ActorResponse.Message)
  return message_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ActorResponse::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Model.ActorResponse.Message)
}
inline void ActorResponse::set_message(const char* value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Model.ActorResponse.Message)
}
inline void ActorResponse::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Model.ActorResponse.Message)
}
inline ::std::string* ActorResponse::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:Model.ActorResponse.Message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ActorResponse::release_message() {
  // @@protoc_insertion_point(field_release:Model.ActorResponse.Message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ActorResponse::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:Model.ActorResponse.Message)
}

// -------------------------------------------------------------------

// A2L_ObjectAddRequest

// optional int32 RpcId = 90;
inline void A2L_ObjectAddRequest::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 A2L_ObjectAddRequest::rpcid() const {
  // @@protoc_insertion_point(field_get:Model.A2L_ObjectAddRequest.RpcId)
  return rpcid_;
}
inline void A2L_ObjectAddRequest::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:Model.A2L_ObjectAddRequest.RpcId)
}

// optional int64 Key = 1;
inline void A2L_ObjectAddRequest::clear_key() {
  key_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 A2L_ObjectAddRequest::key() const {
  // @@protoc_insertion_point(field_get:Model.A2L_ObjectAddRequest.Key)
  return key_;
}
inline void A2L_ObjectAddRequest::set_key(::google::protobuf::int64 value) {
  
  key_ = value;
  // @@protoc_insertion_point(field_set:Model.A2L_ObjectAddRequest.Key)
}

// optional int64 InstanceId = 2;
inline void A2L_ObjectAddRequest::clear_instanceid() {
  instanceid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 A2L_ObjectAddRequest::instanceid() const {
  // @@protoc_insertion_point(field_get:Model.A2L_ObjectAddRequest.InstanceId)
  return instanceid_;
}
inline void A2L_ObjectAddRequest::set_instanceid(::google::protobuf::int64 value) {
  
  instanceid_ = value;
  // @@protoc_insertion_point(field_set:Model.A2L_ObjectAddRequest.InstanceId)
}

// -------------------------------------------------------------------

// L2A_ObjectAddResponse

// optional int32 RpcId = 90;
inline void L2A_ObjectAddResponse::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 L2A_ObjectAddResponse::rpcid() const {
  // @@protoc_insertion_point(field_get:Model.L2A_ObjectAddResponse.RpcId)
  return rpcid_;
}
inline void L2A_ObjectAddResponse::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:Model.L2A_ObjectAddResponse.RpcId)
}

// optional int32 Error = 91;
inline void L2A_ObjectAddResponse::clear_error() {
  error_ = 0;
}
inline ::google::protobuf::int32 L2A_ObjectAddResponse::error() const {
  // @@protoc_insertion_point(field_get:Model.L2A_ObjectAddResponse.Error)
  return error_;
}
inline void L2A_ObjectAddResponse::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:Model.L2A_ObjectAddResponse.Error)
}

// optional string Message = 92;
inline void L2A_ObjectAddResponse::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& L2A_ObjectAddResponse::message() const {
  // @@protoc_insertion_point(field_get:Model.L2A_ObjectAddResponse.Message)
  return message_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void L2A_ObjectAddResponse::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Model.L2A_ObjectAddResponse.Message)
}
inline void L2A_ObjectAddResponse::set_message(const char* value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Model.L2A_ObjectAddResponse.Message)
}
inline void L2A_ObjectAddResponse::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Model.L2A_ObjectAddResponse.Message)
}
inline ::std::string* L2A_ObjectAddResponse::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:Model.L2A_ObjectAddResponse.Message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* L2A_ObjectAddResponse::release_message() {
  // @@protoc_insertion_point(field_release:Model.L2A_ObjectAddResponse.Message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void L2A_ObjectAddResponse::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:Model.L2A_ObjectAddResponse.Message)
}

// -------------------------------------------------------------------

// A2L_ObjectLockRequest

// optional int32 RpcId = 90;
inline void A2L_ObjectLockRequest::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 A2L_ObjectLockRequest::rpcid() const {
  // @@protoc_insertion_point(field_get:Model.A2L_ObjectLockRequest.RpcId)
  return rpcid_;
}
inline void A2L_ObjectLockRequest::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:Model.A2L_ObjectLockRequest.RpcId)
}

// optional int64 Key = 1;
inline void A2L_ObjectLockRequest::clear_key() {
  key_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 A2L_ObjectLockRequest::key() const {
  // @@protoc_insertion_point(field_get:Model.A2L_ObjectLockRequest.Key)
  return key_;
}
inline void A2L_ObjectLockRequest::set_key(::google::protobuf::int64 value) {
  
  key_ = value;
  // @@protoc_insertion_point(field_set:Model.A2L_ObjectLockRequest.Key)
}

// -------------------------------------------------------------------

// L2A_ObjectLockResponse

// optional int32 RpcId = 90;
inline void L2A_ObjectLockResponse::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 L2A_ObjectLockResponse::rpcid() const {
  // @@protoc_insertion_point(field_get:Model.L2A_ObjectLockResponse.RpcId)
  return rpcid_;
}
inline void L2A_ObjectLockResponse::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:Model.L2A_ObjectLockResponse.RpcId)
}

// optional int32 Error = 91;
inline void L2A_ObjectLockResponse::clear_error() {
  error_ = 0;
}
inline ::google::protobuf::int32 L2A_ObjectLockResponse::error() const {
  // @@protoc_insertion_point(field_get:Model.L2A_ObjectLockResponse.Error)
  return error_;
}
inline void L2A_ObjectLockResponse::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:Model.L2A_ObjectLockResponse.Error)
}

// optional string Message = 92;
inline void L2A_ObjectLockResponse::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& L2A_ObjectLockResponse::message() const {
  // @@protoc_insertion_point(field_get:Model.L2A_ObjectLockResponse.Message)
  return message_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void L2A_ObjectLockResponse::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Model.L2A_ObjectLockResponse.Message)
}
inline void L2A_ObjectLockResponse::set_message(const char* value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Model.L2A_ObjectLockResponse.Message)
}
inline void L2A_ObjectLockResponse::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Model.L2A_ObjectLockResponse.Message)
}
inline ::std::string* L2A_ObjectLockResponse::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:Model.L2A_ObjectLockResponse.Message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* L2A_ObjectLockResponse::release_message() {
  // @@protoc_insertion_point(field_release:Model.L2A_ObjectLockResponse.Message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void L2A_ObjectLockResponse::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:Model.L2A_ObjectLockResponse.Message)
}

// -------------------------------------------------------------------

// A2L_ObjectUnLockRequest

// optional int32 RpcId = 90;
inline void A2L_ObjectUnLockRequest::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 A2L_ObjectUnLockRequest::rpcid() const {
  // @@protoc_insertion_point(field_get:Model.A2L_ObjectUnLockRequest.RpcId)
  return rpcid_;
}
inline void A2L_ObjectUnLockRequest::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:Model.A2L_ObjectUnLockRequest.RpcId)
}

// optional int64 Key = 1;
inline void A2L_ObjectUnLockRequest::clear_key() {
  key_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 A2L_ObjectUnLockRequest::key() const {
  // @@protoc_insertion_point(field_get:Model.A2L_ObjectUnLockRequest.Key)
  return key_;
}
inline void A2L_ObjectUnLockRequest::set_key(::google::protobuf::int64 value) {
  
  key_ = value;
  // @@protoc_insertion_point(field_set:Model.A2L_ObjectUnLockRequest.Key)
}

// optional int64 OldInstanceId = 2;
inline void A2L_ObjectUnLockRequest::clear_oldinstanceid() {
  oldinstanceid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 A2L_ObjectUnLockRequest::oldinstanceid() const {
  // @@protoc_insertion_point(field_get:Model.A2L_ObjectUnLockRequest.OldInstanceId)
  return oldinstanceid_;
}
inline void A2L_ObjectUnLockRequest::set_oldinstanceid(::google::protobuf::int64 value) {
  
  oldinstanceid_ = value;
  // @@protoc_insertion_point(field_set:Model.A2L_ObjectUnLockRequest.OldInstanceId)
}

// optional int64 InstanceId = 3;
inline void A2L_ObjectUnLockRequest::clear_instanceid() {
  instanceid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 A2L_ObjectUnLockRequest::instanceid() const {
  // @@protoc_insertion_point(field_get:Model.A2L_ObjectUnLockRequest.InstanceId)
  return instanceid_;
}
inline void A2L_ObjectUnLockRequest::set_instanceid(::google::protobuf::int64 value) {
  
  instanceid_ = value;
  // @@protoc_insertion_point(field_set:Model.A2L_ObjectUnLockRequest.InstanceId)
}

// -------------------------------------------------------------------

// L2A_ObjectUnLockResponse

// optional int32 RpcId = 90;
inline void L2A_ObjectUnLockResponse::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 L2A_ObjectUnLockResponse::rpcid() const {
  // @@protoc_insertion_point(field_get:Model.L2A_ObjectUnLockResponse.RpcId)
  return rpcid_;
}
inline void L2A_ObjectUnLockResponse::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:Model.L2A_ObjectUnLockResponse.RpcId)
}

// optional int32 Error = 91;
inline void L2A_ObjectUnLockResponse::clear_error() {
  error_ = 0;
}
inline ::google::protobuf::int32 L2A_ObjectUnLockResponse::error() const {
  // @@protoc_insertion_point(field_get:Model.L2A_ObjectUnLockResponse.Error)
  return error_;
}
inline void L2A_ObjectUnLockResponse::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:Model.L2A_ObjectUnLockResponse.Error)
}

// optional string Message = 92;
inline void L2A_ObjectUnLockResponse::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& L2A_ObjectUnLockResponse::message() const {
  // @@protoc_insertion_point(field_get:Model.L2A_ObjectUnLockResponse.Message)
  return message_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void L2A_ObjectUnLockResponse::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Model.L2A_ObjectUnLockResponse.Message)
}
inline void L2A_ObjectUnLockResponse::set_message(const char* value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Model.L2A_ObjectUnLockResponse.Message)
}
inline void L2A_ObjectUnLockResponse::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Model.L2A_ObjectUnLockResponse.Message)
}
inline ::std::string* L2A_ObjectUnLockResponse::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:Model.L2A_ObjectUnLockResponse.Message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* L2A_ObjectUnLockResponse::release_message() {
  // @@protoc_insertion_point(field_release:Model.L2A_ObjectUnLockResponse.Message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void L2A_ObjectUnLockResponse::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:Model.L2A_ObjectUnLockResponse.Message)
}

// -------------------------------------------------------------------

// A2L_ObjectRemoveRequest

// optional int32 RpcId = 90;
inline void A2L_ObjectRemoveRequest::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 A2L_ObjectRemoveRequest::rpcid() const {
  // @@protoc_insertion_point(field_get:Model.A2L_ObjectRemoveRequest.RpcId)
  return rpcid_;
}
inline void A2L_ObjectRemoveRequest::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:Model.A2L_ObjectRemoveRequest.RpcId)
}

// optional int64 Key = 1;
inline void A2L_ObjectRemoveRequest::clear_key() {
  key_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 A2L_ObjectRemoveRequest::key() const {
  // @@protoc_insertion_point(field_get:Model.A2L_ObjectRemoveRequest.Key)
  return key_;
}
inline void A2L_ObjectRemoveRequest::set_key(::google::protobuf::int64 value) {
  
  key_ = value;
  // @@protoc_insertion_point(field_set:Model.A2L_ObjectRemoveRequest.Key)
}

// -------------------------------------------------------------------

// L2A_ObjectRemoveResponse

// optional int32 RpcId = 90;
inline void L2A_ObjectRemoveResponse::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 L2A_ObjectRemoveResponse::rpcid() const {
  // @@protoc_insertion_point(field_get:Model.L2A_ObjectRemoveResponse.RpcId)
  return rpcid_;
}
inline void L2A_ObjectRemoveResponse::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:Model.L2A_ObjectRemoveResponse.RpcId)
}

// optional int32 Error = 91;
inline void L2A_ObjectRemoveResponse::clear_error() {
  error_ = 0;
}
inline ::google::protobuf::int32 L2A_ObjectRemoveResponse::error() const {
  // @@protoc_insertion_point(field_get:Model.L2A_ObjectRemoveResponse.Error)
  return error_;
}
inline void L2A_ObjectRemoveResponse::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:Model.L2A_ObjectRemoveResponse.Error)
}

// optional string Message = 92;
inline void L2A_ObjectRemoveResponse::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& L2A_ObjectRemoveResponse::message() const {
  // @@protoc_insertion_point(field_get:Model.L2A_ObjectRemoveResponse.Message)
  return message_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void L2A_ObjectRemoveResponse::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Model.L2A_ObjectRemoveResponse.Message)
}
inline void L2A_ObjectRemoveResponse::set_message(const char* value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Model.L2A_ObjectRemoveResponse.Message)
}
inline void L2A_ObjectRemoveResponse::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Model.L2A_ObjectRemoveResponse.Message)
}
inline ::std::string* L2A_ObjectRemoveResponse::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:Model.L2A_ObjectRemoveResponse.Message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* L2A_ObjectRemoveResponse::release_message() {
  // @@protoc_insertion_point(field_release:Model.L2A_ObjectRemoveResponse.Message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void L2A_ObjectRemoveResponse::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:Model.L2A_ObjectRemoveResponse.Message)
}

// -------------------------------------------------------------------

// A2L_ObjectGetRequest

// optional int32 RpcId = 90;
inline void A2L_ObjectGetRequest::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 A2L_ObjectGetRequest::rpcid() const {
  // @@protoc_insertion_point(field_get:Model.A2L_ObjectGetRequest.RpcId)
  return rpcid_;
}
inline void A2L_ObjectGetRequest::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:Model.A2L_ObjectGetRequest.RpcId)
}

// optional int64 Key = 1;
inline void A2L_ObjectGetRequest::clear_key() {
  key_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 A2L_ObjectGetRequest::key() const {
  // @@protoc_insertion_point(field_get:Model.A2L_ObjectGetRequest.Key)
  return key_;
}
inline void A2L_ObjectGetRequest::set_key(::google::protobuf::int64 value) {
  
  key_ = value;
  // @@protoc_insertion_point(field_set:Model.A2L_ObjectGetRequest.Key)
}

// -------------------------------------------------------------------

// L2A_ObjectGetResponse

// optional int32 RpcId = 90;
inline void L2A_ObjectGetResponse::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 L2A_ObjectGetResponse::rpcid() const {
  // @@protoc_insertion_point(field_get:Model.L2A_ObjectGetResponse.RpcId)
  return rpcid_;
}
inline void L2A_ObjectGetResponse::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:Model.L2A_ObjectGetResponse.RpcId)
}

// optional int32 Error = 91;
inline void L2A_ObjectGetResponse::clear_error() {
  error_ = 0;
}
inline ::google::protobuf::int32 L2A_ObjectGetResponse::error() const {
  // @@protoc_insertion_point(field_get:Model.L2A_ObjectGetResponse.Error)
  return error_;
}
inline void L2A_ObjectGetResponse::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:Model.L2A_ObjectGetResponse.Error)
}

// optional string Message = 92;
inline void L2A_ObjectGetResponse::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& L2A_ObjectGetResponse::message() const {
  // @@protoc_insertion_point(field_get:Model.L2A_ObjectGetResponse.Message)
  return message_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void L2A_ObjectGetResponse::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Model.L2A_ObjectGetResponse.Message)
}
inline void L2A_ObjectGetResponse::set_message(const char* value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Model.L2A_ObjectGetResponse.Message)
}
inline void L2A_ObjectGetResponse::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Model.L2A_ObjectGetResponse.Message)
}
inline ::std::string* L2A_ObjectGetResponse::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:Model.L2A_ObjectGetResponse.Message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* L2A_ObjectGetResponse::release_message() {
  // @@protoc_insertion_point(field_release:Model.L2A_ObjectGetResponse.Message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void L2A_ObjectGetResponse::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:Model.L2A_ObjectGetResponse.Message)
}

// optional int64 InstanceId = 1;
inline void L2A_ObjectGetResponse::clear_instanceid() {
  instanceid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 L2A_ObjectGetResponse::instanceid() const {
  // @@protoc_insertion_point(field_get:Model.L2A_ObjectGetResponse.InstanceId)
  return instanceid_;
}
inline void L2A_ObjectGetResponse::set_instanceid(::google::protobuf::int64 value) {
  
  instanceid_ = value;
  // @@protoc_insertion_point(field_set:Model.L2A_ObjectGetResponse.InstanceId)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Model

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_EtcMsg_2eproto__INCLUDED
