// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EtcMsg.proto

#ifndef PROTOBUF_EtcMsg_2eproto__INCLUDED
#define PROTOBUF_EtcMsg_2eproto__INCLUDED

#include <string>
#include "type/type_factory.h"
#include "opcode/EtcMsgOpcode.h"
#include "module/message/MessageDefines.h"

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#undef GetMessage

namespace Model {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_EtcMsg_2eproto();
void protobuf_AssignDesc_EtcMsg_2eproto();
void protobuf_ShutdownFile_EtcMsg_2eproto();

class ActorMessageTest;
class ActorRequest;
class ActorResponse;
class ActorTestRequest;
class ActorTestResponse;
class MessageHead;
class Struct_Position;
class TestRequest;
class TestResponse;

// ===================================================================

class Struct_Position : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Model.Struct_Position) */ {
 public:
  Struct_Position();
  virtual ~Struct_Position();

  Struct_Position(const Struct_Position& from);

  inline Struct_Position& operator=(const Struct_Position& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Struct_Position& default_instance();

  void Swap(Struct_Position* other);

  // implements Message ----------------------------------------------

  inline Struct_Position* New() const { return New(NULL); }

  Struct_Position* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  virtual Type GetType()const override {return typeof(Struct_Position);}
  void CopyFrom(const Struct_Position& from);
  void MergeFrom(const Struct_Position& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Struct_Position* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // optional int32 y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  ::google::protobuf::int32 y() const;
  void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Model.Struct_Position)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EtcMsg_2eproto();
  friend void protobuf_AssignDesc_EtcMsg_2eproto();
  friend void protobuf_ShutdownFile_EtcMsg_2eproto();

  void InitAsDefaultInstance();
  static Struct_Position* default_instance_;
};
// -------------------------------------------------------------------

class MessageHead : public IMessage /* @@protoc_insertion_point(class_definition:Model.MessageHead) */ {
 public:
  MessageHead();
  virtual ~MessageHead();

  MessageHead(const MessageHead& from);

  inline MessageHead& operator=(const MessageHead& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageHead& default_instance();

  void Swap(MessageHead* other);

  // implements Message ----------------------------------------------

  inline MessageHead* New() const { return New(NULL); }

  MessageHead* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  virtual Type GetType()const override {return typeof(MessageHead);}
  virtual uint16_t GetOpcode()const override {return EtcMsgOpcode::MessageHead;}
  void CopyFrom(const MessageHead& from);
  void MergeFrom(const MessageHead& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MessageHead* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 RpcId = 90;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 90;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // optional int32 Error = 91;
  void clear_error();
  static const int kErrorFieldNumber = 91;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // optional string Message = 92;
  void clear_message();
  static const int kMessageFieldNumber = 92;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // optional int64 ActorId = 93;
  void clear_actorid();
  static const int kActorIdFieldNumber = 93;
  ::google::protobuf::int64 actorid() const;
  void set_actorid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Model.MessageHead)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 rpcid_;
  ::google::protobuf::int32 error_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int64 actorid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EtcMsg_2eproto();
  friend void protobuf_AssignDesc_EtcMsg_2eproto();
  friend void protobuf_ShutdownFile_EtcMsg_2eproto();

  void InitAsDefaultInstance();
  static MessageHead* default_instance_;
};
// -------------------------------------------------------------------

class ActorRequest : public IActorRequest /* @@protoc_insertion_point(class_definition:Model.ActorRequest) */ {
 public:
  ActorRequest();
  virtual ~ActorRequest();

  ActorRequest(const ActorRequest& from);

  inline ActorRequest& operator=(const ActorRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActorRequest& default_instance();

  void Swap(ActorRequest* other);

  // implements Message ----------------------------------------------

  inline ActorRequest* New() const { return New(NULL); }

  ActorRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  virtual Type GetType()const override {return typeof(ActorRequest);}
  virtual int32_t GetRpcId()const override {return rpcid();}
  virtual void SetRpcId(const int32_t val)override { set_rpcid(val);}
  virtual EMessageType GetMessageType()const override {return EMessageType::IActorRequest;}
  virtual uint16_t GetOpcode()const override {return EtcMsgOpcode::ActorRequest;}
  void CopyFrom(const ActorRequest& from);
  void MergeFrom(const ActorRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ActorRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 RpcId = 90;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 90;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Model.ActorRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 rpcid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EtcMsg_2eproto();
  friend void protobuf_AssignDesc_EtcMsg_2eproto();
  friend void protobuf_ShutdownFile_EtcMsg_2eproto();

  void InitAsDefaultInstance();
  static ActorRequest* default_instance_;
};
// -------------------------------------------------------------------

class ActorResponse : public IActorResponse /* @@protoc_insertion_point(class_definition:Model.ActorResponse) */ {
 public:
  ActorResponse();
  virtual ~ActorResponse();

  ActorResponse(const ActorResponse& from);

  inline ActorResponse& operator=(const ActorResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActorResponse& default_instance();

  void Swap(ActorResponse* other);

  // implements Message ----------------------------------------------

  inline ActorResponse* New() const { return New(NULL); }

  ActorResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  virtual Type GetType()const override {return typeof(ActorResponse);}
  virtual int32_t GetError()const override {return error();}
  virtual void SetError(const int32_t val)override { set_error(val);}
  virtual const ::std::string& GetMessage()const override {return message();}
  virtual void SetMessage(const ::std::string& val)override { set_message(val);}
  virtual int32_t GetRpcId()const override {return rpcid();}
  virtual void SetRpcId(const int32_t val)override { set_rpcid(val);}
  virtual EMessageType GetMessageType()const override {return EMessageType::IActorResponse;}
  virtual uint16_t GetOpcode()const override {return EtcMsgOpcode::ActorResponse;}
  void CopyFrom(const ActorResponse& from);
  void MergeFrom(const ActorResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ActorResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 RpcId = 90;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 90;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // optional int32 Error = 91;
  void clear_error();
  static const int kErrorFieldNumber = 91;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // optional string Message = 92;
  void clear_message();
  static const int kMessageFieldNumber = 92;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:Model.ActorResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 rpcid_;
  ::google::protobuf::int32 error_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EtcMsg_2eproto();
  friend void protobuf_AssignDesc_EtcMsg_2eproto();
  friend void protobuf_ShutdownFile_EtcMsg_2eproto();

  void InitAsDefaultInstance();
  static ActorResponse* default_instance_;
};
// -------------------------------------------------------------------

class TestRequest : public IActorLocationRequest /* @@protoc_insertion_point(class_definition:Model.TestRequest) */ {
 public:
  TestRequest();
  virtual ~TestRequest();

  TestRequest(const TestRequest& from);

  inline TestRequest& operator=(const TestRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestRequest& default_instance();

  void Swap(TestRequest* other);

  // implements Message ----------------------------------------------

  inline TestRequest* New() const { return New(NULL); }

  TestRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  virtual Type GetType()const override {return typeof(TestRequest);}
  virtual int32_t GetRpcId()const override {return rpcid();}
  virtual void SetRpcId(const int32_t val)override { set_rpcid(val);}
  virtual EMessageType GetMessageType()const override {return EMessageType::IActorLocationRequest;}
  virtual uint16_t GetOpcode()const override {return EtcMsgOpcode::TestRequest;}
  void CopyFrom(const TestRequest& from);
  void MergeFrom(const TestRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TestRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 A = 1;
  void clear_a();
  static const int kAFieldNumber = 1;
  ::google::protobuf::int32 a() const;
  void set_a(::google::protobuf::int32 value);

  // optional int32 B = 2;
  void clear_b();
  static const int kBFieldNumber = 2;
  ::google::protobuf::int32 b() const;
  void set_b(::google::protobuf::int32 value);

  // optional int32 RpcId = 90;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 90;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Model.TestRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 a_;
  ::google::protobuf::int32 b_;
  ::google::protobuf::int32 rpcid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EtcMsg_2eproto();
  friend void protobuf_AssignDesc_EtcMsg_2eproto();
  friend void protobuf_ShutdownFile_EtcMsg_2eproto();

  void InitAsDefaultInstance();
  static TestRequest* default_instance_;
};
// -------------------------------------------------------------------

class TestResponse : public IActorLocationResponse /* @@protoc_insertion_point(class_definition:Model.TestResponse) */ {
 public:
  TestResponse();
  virtual ~TestResponse();

  TestResponse(const TestResponse& from);

  inline TestResponse& operator=(const TestResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestResponse& default_instance();

  void Swap(TestResponse* other);

  // implements Message ----------------------------------------------

  inline TestResponse* New() const { return New(NULL); }

  TestResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  virtual Type GetType()const override {return typeof(TestResponse);}
  virtual int32_t GetError()const override {return error();}
  virtual void SetError(const int32_t val)override { set_error(val);}
  virtual const ::std::string& GetMessage()const override {return message();}
  virtual void SetMessage(const ::std::string& val)override { set_message(val);}
  virtual int32_t GetRpcId()const override {return rpcid();}
  virtual void SetRpcId(const int32_t val)override { set_rpcid(val);}
  virtual EMessageType GetMessageType()const override {return EMessageType::IActorLocationResponse;}
  virtual uint16_t GetOpcode()const override {return EtcMsgOpcode::TestResponse;}
  void CopyFrom(const TestResponse& from);
  void MergeFrom(const TestResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TestResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 Sum = 1;
  void clear_sum();
  static const int kSumFieldNumber = 1;
  ::google::protobuf::int32 sum() const;
  void set_sum(::google::protobuf::int32 value);

  // optional int32 RpcId = 90;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 90;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // optional int32 Error = 91;
  void clear_error();
  static const int kErrorFieldNumber = 91;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // optional string Message = 92;
  void clear_message();
  static const int kMessageFieldNumber = 92;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:Model.TestResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 sum_;
  ::google::protobuf::int32 rpcid_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int32 error_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EtcMsg_2eproto();
  friend void protobuf_AssignDesc_EtcMsg_2eproto();
  friend void protobuf_ShutdownFile_EtcMsg_2eproto();

  void InitAsDefaultInstance();
  static TestResponse* default_instance_;
};
// -------------------------------------------------------------------

class ActorTestRequest : public IActorRequest /* @@protoc_insertion_point(class_definition:Model.ActorTestRequest) */ {
 public:
  ActorTestRequest();
  virtual ~ActorTestRequest();

  ActorTestRequest(const ActorTestRequest& from);

  inline ActorTestRequest& operator=(const ActorTestRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActorTestRequest& default_instance();

  void Swap(ActorTestRequest* other);

  // implements Message ----------------------------------------------

  inline ActorTestRequest* New() const { return New(NULL); }

  ActorTestRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  virtual Type GetType()const override {return typeof(ActorTestRequest);}
  virtual int32_t GetRpcId()const override {return rpcid();}
  virtual void SetRpcId(const int32_t val)override { set_rpcid(val);}
  virtual EMessageType GetMessageType()const override {return EMessageType::IActorRequest;}
  virtual uint16_t GetOpcode()const override {return EtcMsgOpcode::ActorTestRequest;}
  void CopyFrom(const ActorTestRequest& from);
  void MergeFrom(const ActorTestRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ActorTestRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 A = 1;
  void clear_a();
  static const int kAFieldNumber = 1;
  ::google::protobuf::int32 a() const;
  void set_a(::google::protobuf::int32 value);

  // optional int32 B = 2;
  void clear_b();
  static const int kBFieldNumber = 2;
  ::google::protobuf::int32 b() const;
  void set_b(::google::protobuf::int32 value);

  // optional int32 RpcId = 90;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 90;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // optional int64 ActorId = 93;
  void clear_actorid();
  static const int kActorIdFieldNumber = 93;
  ::google::protobuf::int64 actorid() const;
  void set_actorid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Model.ActorTestRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 a_;
  ::google::protobuf::int32 b_;
  ::google::protobuf::int64 actorid_;
  ::google::protobuf::int32 rpcid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EtcMsg_2eproto();
  friend void protobuf_AssignDesc_EtcMsg_2eproto();
  friend void protobuf_ShutdownFile_EtcMsg_2eproto();

  void InitAsDefaultInstance();
  static ActorTestRequest* default_instance_;
};
// -------------------------------------------------------------------

class ActorTestResponse : public IActorResponse /* @@protoc_insertion_point(class_definition:Model.ActorTestResponse) */ {
 public:
  ActorTestResponse();
  virtual ~ActorTestResponse();

  ActorTestResponse(const ActorTestResponse& from);

  inline ActorTestResponse& operator=(const ActorTestResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActorTestResponse& default_instance();

  void Swap(ActorTestResponse* other);

  // implements Message ----------------------------------------------

  inline ActorTestResponse* New() const { return New(NULL); }

  ActorTestResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  virtual Type GetType()const override {return typeof(ActorTestResponse);}
  virtual int32_t GetError()const override {return error();}
  virtual void SetError(const int32_t val)override { set_error(val);}
  virtual const ::std::string& GetMessage()const override {return message();}
  virtual void SetMessage(const ::std::string& val)override { set_message(val);}
  virtual int32_t GetRpcId()const override {return rpcid();}
  virtual void SetRpcId(const int32_t val)override { set_rpcid(val);}
  virtual EMessageType GetMessageType()const override {return EMessageType::IActorResponse;}
  virtual uint16_t GetOpcode()const override {return EtcMsgOpcode::ActorTestResponse;}
  void CopyFrom(const ActorTestResponse& from);
  void MergeFrom(const ActorTestResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ActorTestResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 Sum = 1;
  void clear_sum();
  static const int kSumFieldNumber = 1;
  ::google::protobuf::int32 sum() const;
  void set_sum(::google::protobuf::int32 value);

  // optional int32 RpcId = 90;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 90;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // optional int32 Error = 91;
  void clear_error();
  static const int kErrorFieldNumber = 91;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // optional string Message = 92;
  void clear_message();
  static const int kMessageFieldNumber = 92;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:Model.ActorTestResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 sum_;
  ::google::protobuf::int32 rpcid_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int32 error_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EtcMsg_2eproto();
  friend void protobuf_AssignDesc_EtcMsg_2eproto();
  friend void protobuf_ShutdownFile_EtcMsg_2eproto();

  void InitAsDefaultInstance();
  static ActorTestResponse* default_instance_;
};
// -------------------------------------------------------------------

class ActorMessageTest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Model.ActorMessageTest) */ {
 public:
  ActorMessageTest();
  virtual ~ActorMessageTest();

  ActorMessageTest(const ActorMessageTest& from);

  inline ActorMessageTest& operator=(const ActorMessageTest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActorMessageTest& default_instance();

  void Swap(ActorMessageTest* other);

  // implements Message ----------------------------------------------

  inline ActorMessageTest* New() const { return New(NULL); }

  ActorMessageTest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  virtual Type GetType()const override {return typeof(ActorMessageTest);}
  void CopyFrom(const ActorMessageTest& from);
  void MergeFrom(const ActorMessageTest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ActorMessageTest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Model.ActorMessageTest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EtcMsg_2eproto();
  friend void protobuf_AssignDesc_EtcMsg_2eproto();
  friend void protobuf_ShutdownFile_EtcMsg_2eproto();

  void InitAsDefaultInstance();
  static ActorMessageTest* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Struct_Position

// optional int32 x = 1;
inline void Struct_Position::clear_x() {
  x_ = 0;
}
inline ::google::protobuf::int32 Struct_Position::x() const {
  // @@protoc_insertion_point(field_get:Model.Struct_Position.x)
  return x_;
}
inline void Struct_Position::set_x(::google::protobuf::int32 value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:Model.Struct_Position.x)
}

// optional int32 y = 2;
inline void Struct_Position::clear_y() {
  y_ = 0;
}
inline ::google::protobuf::int32 Struct_Position::y() const {
  // @@protoc_insertion_point(field_get:Model.Struct_Position.y)
  return y_;
}
inline void Struct_Position::set_y(::google::protobuf::int32 value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:Model.Struct_Position.y)
}

// -------------------------------------------------------------------

// MessageHead

// optional int32 RpcId = 90;
inline void MessageHead::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 MessageHead::rpcid() const {
  // @@protoc_insertion_point(field_get:Model.MessageHead.RpcId)
  return rpcid_;
}
inline void MessageHead::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:Model.MessageHead.RpcId)
}

// optional int32 Error = 91;
inline void MessageHead::clear_error() {
  error_ = 0;
}
inline ::google::protobuf::int32 MessageHead::error() const {
  // @@protoc_insertion_point(field_get:Model.MessageHead.Error)
  return error_;
}
inline void MessageHead::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:Model.MessageHead.Error)
}

// optional string Message = 92;
inline void MessageHead::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MessageHead::message() const {
  // @@protoc_insertion_point(field_get:Model.MessageHead.Message)
  return message_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageHead::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Model.MessageHead.Message)
}
inline void MessageHead::set_message(const char* value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Model.MessageHead.Message)
}
inline void MessageHead::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Model.MessageHead.Message)
}
inline ::std::string* MessageHead::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:Model.MessageHead.Message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MessageHead::release_message() {
  // @@protoc_insertion_point(field_release:Model.MessageHead.Message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageHead::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:Model.MessageHead.Message)
}

// optional int64 ActorId = 93;
inline void MessageHead::clear_actorid() {
  actorid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 MessageHead::actorid() const {
  // @@protoc_insertion_point(field_get:Model.MessageHead.ActorId)
  return actorid_;
}
inline void MessageHead::set_actorid(::google::protobuf::int64 value) {
  
  actorid_ = value;
  // @@protoc_insertion_point(field_set:Model.MessageHead.ActorId)
}

// -------------------------------------------------------------------

// ActorRequest

// optional int32 RpcId = 90;
inline void ActorRequest::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 ActorRequest::rpcid() const {
  // @@protoc_insertion_point(field_get:Model.ActorRequest.RpcId)
  return rpcid_;
}
inline void ActorRequest::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:Model.ActorRequest.RpcId)
}

// -------------------------------------------------------------------

// ActorResponse

// optional int32 RpcId = 90;
inline void ActorResponse::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 ActorResponse::rpcid() const {
  // @@protoc_insertion_point(field_get:Model.ActorResponse.RpcId)
  return rpcid_;
}
inline void ActorResponse::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:Model.ActorResponse.RpcId)
}

// optional int32 Error = 91;
inline void ActorResponse::clear_error() {
  error_ = 0;
}
inline ::google::protobuf::int32 ActorResponse::error() const {
  // @@protoc_insertion_point(field_get:Model.ActorResponse.Error)
  return error_;
}
inline void ActorResponse::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:Model.ActorResponse.Error)
}

// optional string Message = 92;
inline void ActorResponse::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ActorResponse::message() const {
  // @@protoc_insertion_point(field_get:Model.ActorResponse.Message)
  return message_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ActorResponse::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Model.ActorResponse.Message)
}
inline void ActorResponse::set_message(const char* value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Model.ActorResponse.Message)
}
inline void ActorResponse::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Model.ActorResponse.Message)
}
inline ::std::string* ActorResponse::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:Model.ActorResponse.Message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ActorResponse::release_message() {
  // @@protoc_insertion_point(field_release:Model.ActorResponse.Message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ActorResponse::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:Model.ActorResponse.Message)
}

// -------------------------------------------------------------------

// TestRequest

// optional int32 A = 1;
inline void TestRequest::clear_a() {
  a_ = 0;
}
inline ::google::protobuf::int32 TestRequest::a() const {
  // @@protoc_insertion_point(field_get:Model.TestRequest.A)
  return a_;
}
inline void TestRequest::set_a(::google::protobuf::int32 value) {
  
  a_ = value;
  // @@protoc_insertion_point(field_set:Model.TestRequest.A)
}

// optional int32 B = 2;
inline void TestRequest::clear_b() {
  b_ = 0;
}
inline ::google::protobuf::int32 TestRequest::b() const {
  // @@protoc_insertion_point(field_get:Model.TestRequest.B)
  return b_;
}
inline void TestRequest::set_b(::google::protobuf::int32 value) {
  
  b_ = value;
  // @@protoc_insertion_point(field_set:Model.TestRequest.B)
}

// optional int32 RpcId = 90;
inline void TestRequest::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 TestRequest::rpcid() const {
  // @@protoc_insertion_point(field_get:Model.TestRequest.RpcId)
  return rpcid_;
}
inline void TestRequest::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:Model.TestRequest.RpcId)
}

// -------------------------------------------------------------------

// TestResponse

// optional int32 Sum = 1;
inline void TestResponse::clear_sum() {
  sum_ = 0;
}
inline ::google::protobuf::int32 TestResponse::sum() const {
  // @@protoc_insertion_point(field_get:Model.TestResponse.Sum)
  return sum_;
}
inline void TestResponse::set_sum(::google::protobuf::int32 value) {
  
  sum_ = value;
  // @@protoc_insertion_point(field_set:Model.TestResponse.Sum)
}

// optional int32 RpcId = 90;
inline void TestResponse::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 TestResponse::rpcid() const {
  // @@protoc_insertion_point(field_get:Model.TestResponse.RpcId)
  return rpcid_;
}
inline void TestResponse::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:Model.TestResponse.RpcId)
}

// optional int32 Error = 91;
inline void TestResponse::clear_error() {
  error_ = 0;
}
inline ::google::protobuf::int32 TestResponse::error() const {
  // @@protoc_insertion_point(field_get:Model.TestResponse.Error)
  return error_;
}
inline void TestResponse::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:Model.TestResponse.Error)
}

// optional string Message = 92;
inline void TestResponse::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TestResponse::message() const {
  // @@protoc_insertion_point(field_get:Model.TestResponse.Message)
  return message_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TestResponse::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Model.TestResponse.Message)
}
inline void TestResponse::set_message(const char* value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Model.TestResponse.Message)
}
inline void TestResponse::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Model.TestResponse.Message)
}
inline ::std::string* TestResponse::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:Model.TestResponse.Message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TestResponse::release_message() {
  // @@protoc_insertion_point(field_release:Model.TestResponse.Message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TestResponse::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:Model.TestResponse.Message)
}

// -------------------------------------------------------------------

// ActorTestRequest

// optional int32 A = 1;
inline void ActorTestRequest::clear_a() {
  a_ = 0;
}
inline ::google::protobuf::int32 ActorTestRequest::a() const {
  // @@protoc_insertion_point(field_get:Model.ActorTestRequest.A)
  return a_;
}
inline void ActorTestRequest::set_a(::google::protobuf::int32 value) {
  
  a_ = value;
  // @@protoc_insertion_point(field_set:Model.ActorTestRequest.A)
}

// optional int32 B = 2;
inline void ActorTestRequest::clear_b() {
  b_ = 0;
}
inline ::google::protobuf::int32 ActorTestRequest::b() const {
  // @@protoc_insertion_point(field_get:Model.ActorTestRequest.B)
  return b_;
}
inline void ActorTestRequest::set_b(::google::protobuf::int32 value) {
  
  b_ = value;
  // @@protoc_insertion_point(field_set:Model.ActorTestRequest.B)
}

// optional int32 RpcId = 90;
inline void ActorTestRequest::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 ActorTestRequest::rpcid() const {
  // @@protoc_insertion_point(field_get:Model.ActorTestRequest.RpcId)
  return rpcid_;
}
inline void ActorTestRequest::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:Model.ActorTestRequest.RpcId)
}

// optional int64 ActorId = 93;
inline void ActorTestRequest::clear_actorid() {
  actorid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 ActorTestRequest::actorid() const {
  // @@protoc_insertion_point(field_get:Model.ActorTestRequest.ActorId)
  return actorid_;
}
inline void ActorTestRequest::set_actorid(::google::protobuf::int64 value) {
  
  actorid_ = value;
  // @@protoc_insertion_point(field_set:Model.ActorTestRequest.ActorId)
}

// -------------------------------------------------------------------

// ActorTestResponse

// optional int32 Sum = 1;
inline void ActorTestResponse::clear_sum() {
  sum_ = 0;
}
inline ::google::protobuf::int32 ActorTestResponse::sum() const {
  // @@protoc_insertion_point(field_get:Model.ActorTestResponse.Sum)
  return sum_;
}
inline void ActorTestResponse::set_sum(::google::protobuf::int32 value) {
  
  sum_ = value;
  // @@protoc_insertion_point(field_set:Model.ActorTestResponse.Sum)
}

// optional int32 RpcId = 90;
inline void ActorTestResponse::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 ActorTestResponse::rpcid() const {
  // @@protoc_insertion_point(field_get:Model.ActorTestResponse.RpcId)
  return rpcid_;
}
inline void ActorTestResponse::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:Model.ActorTestResponse.RpcId)
}

// optional int32 Error = 91;
inline void ActorTestResponse::clear_error() {
  error_ = 0;
}
inline ::google::protobuf::int32 ActorTestResponse::error() const {
  // @@protoc_insertion_point(field_get:Model.ActorTestResponse.Error)
  return error_;
}
inline void ActorTestResponse::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:Model.ActorTestResponse.Error)
}

// optional string Message = 92;
inline void ActorTestResponse::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ActorTestResponse::message() const {
  // @@protoc_insertion_point(field_get:Model.ActorTestResponse.Message)
  return message_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ActorTestResponse::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Model.ActorTestResponse.Message)
}
inline void ActorTestResponse::set_message(const char* value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Model.ActorTestResponse.Message)
}
inline void ActorTestResponse::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Model.ActorTestResponse.Message)
}
inline ::std::string* ActorTestResponse::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:Model.ActorTestResponse.Message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ActorTestResponse::release_message() {
  // @@protoc_insertion_point(field_release:Model.ActorTestResponse.Message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ActorTestResponse::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:Model.ActorTestResponse.Message)
}

// -------------------------------------------------------------------

// ActorMessageTest

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Model

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_EtcMsg_2eproto__INCLUDED
